### ISSUE TITLE
Missing example font

### ISSUE THREAD

**Issue by pga23** [desertkun/SH1106#1]
Your library works very well - thanks a lot for your effort.
Could you please add any example font to use by your library or any tool to generate it?

**Comment by desertkun** [comment]
Cant help much with generation, because I ended up stealing those two from around the internet: [5x7](https://github.com/desertkun/pods/blob/master/inc/font5x7.h) and [7x10](https://github.com/desertkun/pods/blob/master/inc/font7x10.h). Use example can be found in [my parent project](https://github.com/desertkun/pods).
